### ISSUE TITLE
make board error

### ISSUE THREAD

**Issue by elshill** [mit-acl/sfpro-dev#1]
Hello! 
I am new to docker and the sfpro, but need to learn how to use it for work! I came across this dev environment and followed the instructions, but when I got to `make build` , I was getting this error on step 3: `standard_init_linux.go:207: exec user process caused "exec format error"`, and the command: 
`RUN cd /home/root && \
    git clone -b 3.3.3 --single-branch --depth 1 https://github.com/eigenteam/eigen-git-mirror eigen && \
    mkdir eigen/build && cd eigen/build && cmake .. && make install && \
    cd /home/root && rm -rf eigen` 
returned a non-zero code:1

Was wondering if you have any advice about what's up :)

**Comment by plusk01** [comment]
This kind of sounds like an architecture mismatch. What platform are you running `make board` on? (I'm assuming you meant this as opposed to `make build`)

**Comment by plusk01** [comment]
Actually, I just realized why this is happening. The [docker page on the Intrinsyc wiki](https://tech.intrinsyc.com/projects/qualcomm-flight-pro-development-kit/wiki/docker) says

> Note: If you are seeing "exec format error" when launching Docker then please install the following & retry:

> `sudo apt-get install qemu-user-static`

After installing `qemu-user-static` the `make board` command worked for me.
